/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameZkMinesRouteImport } from './routes/game/zk-mines'
import { Route as GameSpeedOLightRouteImport } from './routes/game/speed-o-light'
import { Route as GameCardWarsIndexRouteImport } from './routes/game/card-wars/index'
import { Route as GameCardWarsPlayRouteImport } from './routes/game/card-wars/play'
import { Route as GameCardWarsLobbyRouteImport } from './routes/game/card-wars/lobby'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameZkMinesRoute = GameZkMinesRouteImport.update({
  id: '/game/zk-mines',
  path: '/game/zk-mines',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSpeedOLightRoute = GameSpeedOLightRouteImport.update({
  id: '/game/speed-o-light',
  path: '/game/speed-o-light',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCardWarsIndexRoute = GameCardWarsIndexRouteImport.update({
  id: '/game/card-wars/',
  path: '/game/card-wars/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCardWarsPlayRoute = GameCardWarsPlayRouteImport.update({
  id: '/game/card-wars/play',
  path: '/game/card-wars/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCardWarsLobbyRoute = GameCardWarsLobbyRouteImport.update({
  id: '/game/card-wars/lobby',
  path: '/game/card-wars/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/speed-o-light': typeof GameSpeedOLightRoute
  '/game/zk-mines': typeof GameZkMinesRoute
  '/game/card-wars/lobby': typeof GameCardWarsLobbyRoute
  '/game/card-wars/play': typeof GameCardWarsPlayRoute
  '/game/card-wars/': typeof GameCardWarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/speed-o-light': typeof GameSpeedOLightRoute
  '/game/zk-mines': typeof GameZkMinesRoute
  '/game/card-wars/lobby': typeof GameCardWarsLobbyRoute
  '/game/card-wars/play': typeof GameCardWarsPlayRoute
  '/game/card-wars': typeof GameCardWarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/speed-o-light': typeof GameSpeedOLightRoute
  '/game/zk-mines': typeof GameZkMinesRoute
  '/game/card-wars/lobby': typeof GameCardWarsLobbyRoute
  '/game/card-wars/play': typeof GameCardWarsPlayRoute
  '/game/card-wars/': typeof GameCardWarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/speed-o-light'
    | '/game/zk-mines'
    | '/game/card-wars/lobby'
    | '/game/card-wars/play'
    | '/game/card-wars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/speed-o-light'
    | '/game/zk-mines'
    | '/game/card-wars/lobby'
    | '/game/card-wars/play'
    | '/game/card-wars'
  id:
    | '__root__'
    | '/'
    | '/game/speed-o-light'
    | '/game/zk-mines'
    | '/game/card-wars/lobby'
    | '/game/card-wars/play'
    | '/game/card-wars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameSpeedOLightRoute: typeof GameSpeedOLightRoute
  GameZkMinesRoute: typeof GameZkMinesRoute
  GameCardWarsLobbyRoute: typeof GameCardWarsLobbyRoute
  GameCardWarsPlayRoute: typeof GameCardWarsPlayRoute
  GameCardWarsIndexRoute: typeof GameCardWarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/zk-mines': {
      id: '/game/zk-mines'
      path: '/game/zk-mines'
      fullPath: '/game/zk-mines'
      preLoaderRoute: typeof GameZkMinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/speed-o-light': {
      id: '/game/speed-o-light'
      path: '/game/speed-o-light'
      fullPath: '/game/speed-o-light'
      preLoaderRoute: typeof GameSpeedOLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/card-wars/': {
      id: '/game/card-wars/'
      path: '/game/card-wars'
      fullPath: '/game/card-wars/'
      preLoaderRoute: typeof GameCardWarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/card-wars/play': {
      id: '/game/card-wars/play'
      path: '/game/card-wars/play'
      fullPath: '/game/card-wars/play'
      preLoaderRoute: typeof GameCardWarsPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/card-wars/lobby': {
      id: '/game/card-wars/lobby'
      path: '/game/card-wars/lobby'
      fullPath: '/game/card-wars/lobby'
      preLoaderRoute: typeof GameCardWarsLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameSpeedOLightRoute: GameSpeedOLightRoute,
  GameZkMinesRoute: GameZkMinesRoute,
  GameCardWarsLobbyRoute: GameCardWarsLobbyRoute,
  GameCardWarsPlayRoute: GameCardWarsPlayRoute,
  GameCardWarsIndexRoute: GameCardWarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
