// GameRegistry ABI (the subset the backend + clients use). Env-free so it can
// be imported from any layer. The Result tuple components MUST match the
// Solidity struct field order exactly — see GameRegistry.sol.
// Generated from GameRegistry_abi.json; keep in sync after recompiling.

export const gameRegistryAbi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [{ name: "_signer", type: "address" }],
  },
  {
    type: "function",
    name: "finalizeSession",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "r",
        type: "tuple",
        components: [
          { name: "sessionId", type: "bytes32" },
          { name: "seedTxHash", type: "bytes32" },
          { name: "playerA", type: "address" },
          { name: "playerB", type: "address" },
          { name: "xpA", type: "uint128" },
          { name: "xpB", type: "uint128" },
          { name: "result", type: "uint8" },
          { name: "deckCommitment", type: "bytes32" },
          { name: "handCommitmentA", type: "bytes32" },
          { name: "handCommitmentB", type: "bytes32" },
          { name: "deadline", type: "uint256" },
        ],
      },
      { name: "sig", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getPlayerStats",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "totalXp", type: "uint256" },
          { name: "sessionsPlayed", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "setSigner",
    stateMutability: "nonpayable",
    inputs: [{ name: "_signer", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "sessionStatus",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "signer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "stats",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "totalXp", type: "uint256" },
      { name: "sessionsPlayed", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "pendingOwner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptOwnership",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "eip712Domain",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1" },
      { name: "name", type: "string" },
      { name: "version", type: "string" },
      { name: "chainId", type: "uint256" },
      { name: "verifyingContract", type: "address" },
      { name: "salt", type: "bytes32" },
      { name: "extensions", type: "uint256[]" },
    ],
  },
  {
    type: "event",
    name: "SessionFinalized",
    anonymous: false,
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "playerA", type: "address", indexed: true },
      { name: "playerB", type: "address", indexed: true },
      { name: "xpA", type: "uint128", indexed: false },
      { name: "xpB", type: "uint128", indexed: false },
      { name: "result", type: "uint8", indexed: false },
      { name: "seedTxHash", type: "bytes32", indexed: false },
      { name: "deckCommitment", type: "bytes32", indexed: false },
      { name: "handCommitmentA", type: "bytes32", indexed: false },
      { name: "handCommitmentB", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SignerUpdated",
    anonymous: false,
    inputs: [{ name: "newSigner", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    anonymous: false,
    inputs: [
      { name: "previousOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    anonymous: false,
    inputs: [
      { name: "previousOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "EIP712DomainChanged",
    anonymous: false,
    inputs: [],
  },
  { type: "error", name: "SessionAlreadyFinalized", inputs: [] },
  { type: "error", name: "DeadlinePassed", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidPlayers", inputs: [] },
  { type: "error", name: "InvalidSigner", inputs: [] },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [{ name: "length", type: "uint256" }],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureS",
    inputs: [{ name: "s", type: "bytes32" }],
  },
  { type: "error", name: "InvalidShortString", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address" }],
  },
  {
    type: "error",
    name: "StringTooLong",
    inputs: [{ name: "str", type: "string" }],
  },
] as const;
